In [1]:
import numpy as np

print("RUDRAEDGE RE-T1 - Day 3")
print("NumPy Numerical Processing")
print("--------------------------")

print("NumPy Version:", np.__version__)

RUDRAEDGE RE-T1 - Day 3
NumPy Numerical Processing
--------------------------
NumPy Version: 2.5.3


In [2]:
# 1D sensor data array

temperature = np.array([24.5, 25.1, 26.3, 27.0, 26.7, 25.9])

print("Temperature Data:")
print(temperature)

print("\nArray Shape:", temperature.shape)
print("Array Size:", temperature.size)
print("Data Type:", temperature.dtype)

Temperature Data:
[24.5 25.1 26.3 27.  26.7 25.9]

Array Shape: (6,)
Array Size: 6
Data Type: float64


In [3]:
# Accessing individual values using indexing

print("First Temperature:", temperature[0])
print("Third Temperature:", temperature[2])
print("Last Temperature:", temperature[-1])

# Slicing the array

print("\nFirst Three Readings:", temperature[:3])
print("Last Three Readings:", temperature[-3:])

First Temperature: 24.5
Third Temperature: 26.3
Last Temperature: 25.9

First Three Readings: [24.5 25.1 26.3]
Last Three Readings: [27.  26.7 25.9]


In [4]:
# NumPy array arithmetic operations

temperature_c = np.array([24.5, 25.1, 26.3, 27.0, 26.7, 25.9])

# Increase every temperature by 2°C
increased_temp = temperature_c + 2

# Convert Celsius to Fahrenheit
temperature_f = (temperature_c * 9/5) + 32

# Difference from a reference temperature
reference_temp = 25
temperature_difference = temperature_c - reference_temp

print("Original Temperature (°C):")
print(temperature_c)

print("\nTemperature after +2°C:")
print(increased_temp)

print("\nTemperature in Fahrenheit:")
print(temperature_f)

print("\nDifference from 25°C:")
print(temperature_difference)

Original Temperature (°C):
[24.5 25.1 26.3 27.  26.7 25.9]

Temperature after +2°C:
[26.5 27.1 28.3 29.  28.7 27.9]

Temperature in Fahrenheit:
[76.1  77.18 79.34 80.6  80.06 78.62]

Difference from 25°C:
[-0.5  0.1  1.3  2.   1.7  0.9]


In [5]:
# Statistical operations on sensor data

print("Minimum Temperature:", np.min(temperature_c))
print("Maximum Temperature:", np.max(temperature_c))
print("Mean Temperature:", np.mean(temperature_c))
print("Median Temperature:", np.median(temperature_c))
print("Standard Deviation:", np.std(temperature_c))

Minimum Temperature: 24.5
Maximum Temperature: 27.0
Mean Temperature: 25.916666666666668
Median Temperature: 26.1
Standard Deviation: 0.8763877883423268


In [6]:
# Filtering sensor data using conditions

high_temperature = temperature_c[temperature_c > 26]

print("Temperatures above 26°C:")
print(high_temperature)

# Create a condition for normal temperature range
normal_temperature = temperature_c[
    (temperature_c >= 25) & (temperature_c <= 27)
]

print("\nTemperatures between 25°C and 27°C:")
print(normal_temperature)

Temperatures above 26°C:
[26.3 27.  26.7]

Temperatures between 25°C and 27°C:
[25.1 26.3 27.  26.7 25.9]


In [9]:
# 2D array representing multiple sensor readings

sensor_data = np.array([
    [24.5, 1012.3, 11.8],
    [25.1, 1011.8, 11.9],
    [26.3, 1011.2, 12.0],
    [27.0, 1010.7, 12.1],
    [26.7, 1010.9, 12.0]
])

print("Sensor Data:")
print(sensor_data)

print("\nShape:", sensor_data.shape)
print("Rows:", sensor_data.shape[0])
print("Columns:", sensor_data.shape[1])

Sensor Data:
[[  24.5 1012.3   11.8]
 [  25.1 1011.8   11.9]
 [  26.3 1011.2   12. ]
 [  27.  1010.7   12.1]
 [  26.7 1010.9   12. ]]

Shape: (5, 3)
Rows: 5
Columns: 3


In [8]:
# Accessing data from a 2D NumPy array

print("First Row:")
print(sensor_data[0])

print("\nTemperature Column:")
print(sensor_data[:, 0])

print("\nPressure Column:")
print(sensor_data[:, 1])

print("\nVoltage Column:")
print(sensor_data[:, 2])

First Row:
[  24.5 1012.3   11.8]

Temperature Column:
[24.5 25.1 26.3 27.  26.7]

Pressure Column:
[1012.3 1011.8 1011.2 1010.7 1010.9]

Voltage Column:
[11.8 11.9 12.  12.1 12. ]


In [10]:
# Vectorized numerical processing

# Apply calibration to all temperature readings
calibrated_temperature = temperature_c * 1.02 + 0.5

print("Original Temperature:")
print(temperature_c)

print("\nCalibrated Temperature:")
print(calibrated_temperature)

Original Temperature:
[24.5 25.1 26.3 27.  26.7 25.9]

Calibrated Temperature:
[25.49  26.102 27.326 28.04  27.734 26.918]


In [11]:
# Comparing normal Python loop with NumPy vectorization

import time

data = np.random.random(1_000_000)

# Normal Python loop
start_loop = time.perf_counter()

loop_result = []
for value in data:
    loop_result.append(value * 2)

loop_time = time.perf_counter() - start_loop


# NumPy vectorized operation
start_vectorized = time.perf_counter()

vectorized_result = data * 2

vectorized_time = time.perf_counter() - start_vectorized


print("Loop Processing Time:", loop_time, "seconds")
print("Vectorized Processing Time:", vectorized_time, "seconds")

if vectorized_time > 0:
    print(
        "Speed Improvement:",
        round(loop_time / vectorized_time, 2),
        "x"
    )

Loop Processing Time: 0.6644890999996278 seconds
Vectorized Processing Time: 0.005350299999918207 seconds
Speed Improvement: 124.2 x


In [12]:
# Synthetic telemetry data using NumPy

np.random.seed(42)

samples = 1000

temperature = np.random.uniform(20, 35, samples)
pressure = np.random.uniform(990, 1030, samples)
voltage = np.random.uniform(11, 13, samples)
altitude = np.random.uniform(100, 500, samples)
speed = np.random.uniform(20, 80, samples)

print("Synthetic Telemetry Generated")
print("-----------------------------")
print("Number of Samples:", samples)

print("\nFirst 5 Temperature Values:")
print(temperature[:5])

print("\nFirst 5 Pressure Values:")
print(pressure[:5])

print("\nFirst 5 Voltage Values:")
print(voltage[:5])

print("\nFirst 5 Altitude Values:")
print(altitude[:5])

print("\nFirst 5 Speed Values:")
print(speed[:5])

Synthetic Telemetry Generated
-----------------------------
Number of Samples: 1000

First 5 Temperature Values:
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961]

First 5 Pressure Values:
[ 997.40531715 1011.6760379  1024.91783344 1019.28899546 1022.26244591]

First 5 Voltage Values:
[11.52341137 11.4939576  12.81250916 11.4990924  11.54389945]

First 5 Altitude Values:
[369.08119768 418.67255888 200.18715952 349.94963984 328.69839326]

First 5 Speed Values:
[54.3197527  68.32593976 65.60965579 29.23399428 28.95496818]


In [13]:
# Statistical analysis of synthetic telemetry

print("Telemetry Statistics")
print("--------------------")

print("Temperature Mean:", np.mean(temperature))
print("Temperature Min:", np.min(temperature))
print("Temperature Max:", np.max(temperature))

print("\nPressure Mean:", np.mean(pressure))
print("Pressure Min:", np.min(pressure))
print("Pressure Max:", np.max(pressure))

print("\nVoltage Mean:", np.mean(voltage))
print("Voltage Min:", np.min(voltage))
print("Voltage Max:", np.max(voltage))

print("\nAltitude Mean:", np.mean(altitude))
print("Altitude Min:", np.min(altitude))
print("Altitude Max:", np.max(altitude))

print("\nSpeed Mean:", np.mean(speed))
print("Speed Min:", np.min(speed))
print("Speed Max:", np.max(speed))


Telemetry Statistics
--------------------
Temperature Mean: 27.353848299802003
Temperature Min: 20.069480345069042
Temperature Max: 34.99576509929196

Pressure Mean: 1010.2806922071682
Pressure Min: 990.1287305441712
Pressure Max: 1029.9765490308266

Voltage Mean: 12.00481145220718
Voltage Min: 11.000023269510733
Voltage Max: 12.995641711363957

Altitude Mean: 296.15001911498655
Altitude Min: 100.26135630451982
Altitude Max: 499.82308130017543

Speed Mean: 49.64631935370326
Speed Min: 20.001843130722946
Speed Max: 79.86496334061204


In [14]:
# Telemetry validation using NumPy conditions

temperature_valid = (temperature >= 20) & (temperature <= 35)
pressure_valid = (pressure >= 990) & (pressure <= 1030)
voltage_valid = (voltage >= 11) & (voltage <= 13)
altitude_valid = (altitude >= 100) & (altitude <= 500)
speed_valid = (speed >= 20) & (speed <= 80)

print("Telemetry Validation")
print("--------------------")

print("Valid Temperature Readings:", np.sum(temperature_valid))
print("Valid Pressure Readings:", np.sum(pressure_valid))
print("Valid Voltage Readings:", np.sum(voltage_valid))
print("Valid Altitude Readings:", np.sum(altitude_valid))
print("Valid Speed Readings:", np.sum(speed_valid))

print("\nTotal Samples:", samples)

Telemetry Validation
--------------------
Valid Temperature Readings: 1000
Valid Pressure Readings: 1000
Valid Voltage Readings: 1000
Valid Altitude Readings: 1000
Valid Speed Readings: 1000

Total Samples: 1000


In [16]:
# NumPy broadcasting

sensor_readings = np.array([
    [24.5, 1012.3, 11.8],
    [25.1, 1011.8, 11.9],
    [26.3, 1011.2, 12.0],
    [27.0, 1010.7, 12.1],
    [26.7, 1010.9, 12.0]
])

# Calibration offset for each sensor
calibration_offset = np.array([0.5, 2.0, 0.1])

calibrated_data = sensor_readings + calibration_offset

print("Original Sensor Data:")
print(sensor_readings)

print("\nCalibration Offset:")
print(calibration_offset)

print("\nCalibrated Sensor Data:")
print(calibrated_data)

Original Sensor Data:
[[  24.5 1012.3   11.8]
 [  25.1 1011.8   11.9]
 [  26.3 1011.2   12. ]
 [  27.  1010.7   12.1]
 [  26.7 1010.9   12. ]]

Calibration Offset:
[0.5 2.  0.1]

Calibrated Sensor Data:
[[  25.  1014.3   11.9]
 [  25.6 1013.8   12. ]
 [  26.8 1013.2   12.1]
 [  27.5 1012.7   12.2]
 [  27.2 1012.9   12.1]]


In [17]:
# Numerical processing routine

data = np.array([10, 20, 30, 40, 50], dtype=float)

addition_result = data + 5
multiplication_result = data * 2
square_result = data ** 2
sqrt_result = np.sqrt(data)

print("Original Data:")
print(data)

print("\nAfter Addition (+5):")
print(addition_result)

print("\nAfter Multiplication (×2):")
print(multiplication_result)

print("\nSquare of Data:")
print(square_result)

print("\nSquare Root of Data:")
print(sqrt_result)

Original Data:
[10. 20. 30. 40. 50.]

After Addition (+5):
[15. 25. 35. 45. 55.]

After Multiplication (×2):
[ 20.  40.  60.  80. 100.]

Square of Data:
[ 100.  400.  900. 1600. 2500.]

Square Root of Data:
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
